trace: fix: compilation errors
this commit fixes the following errors:
  error: implicit declaration of function 'get_backtrace' [-Werror,-Wimplicit-function-declaration]
  error: cast to 'void *' from smaller integer type 'int' [-Werror,-Wint-to-void-pointer-cast]

error introduced in commit 59b017d

Change-Id: Ic07f5176ef9658c0115843bcdbff6ad0f41a57c1
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>