f2fs: fix compilation errors
this commit fixes the following error:
  error: use of undeclared identifier 'ui'

this error was introduced in commit a6a44c3

Change-Id: I26801d348b4e19fd84734988c7ee1930598d829c
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>